### PR TITLE
Updated FileUploadDialog TIFF upload to use 'add_or_update_image_datasource' per backend agreement in spec document

### PR DESCRIPTION
**Pull request by aleql**
Aligned TIFF upload functionality in FileUploadDialog with agreed backend endpoint
- Updated TIFF upload to use 'add_or_update_image_datasource' as per backend agreement
- Added 'tiffMetadata' and 'datasourceName' fields to the request body, and the tiff image to the payload for TIFF uploads
- Retained CSV upload functionality to 'add_datasource' endpoint

### CODE REVIEW

**Comment by xinaesthete** [comment]
Hi @aleql I think you need to redo this against latest main - I merged your other PR but it conflicts with this. Also this commit has formatting mixed in with the actual code changes.

**Comment by aleql** [comment]
Hello Pete,

I’ve resolved the formatting issues that were preventing the merge of the add_or_update_image_datasource PR into master, so it can now be merged without conflicts.

Additionally, I’ve implemented two small fixes:

- Addressed the issue raised by Jayesh, where the upload form wasn’t selecting the default datasource name for the payload.

- Fixed the console warning that appeared when processing a CSV file due to a wrong DOM nesting.

**Comment by xinaesthete** [comment]
Hi @aleql, sorry I haven't responded sooner,

The thing is there's still a lot of formatting-related noise that appears when I try to review the differences between this & main... I was hoping you might rebase from that or something so that there'd be less of that distracting in 'files changed' etc. We could try adding more entries to `.git-blame-ignore-revs`, or what I was hoping for was a version of this that really just had the salient points...

**Comment by aleql** [comment]
Hello Pete,
I have performed a rebase on the branch to incorporate the latest changes from master and added the formatting commit hashes to .git-blame-ignore-revs. This should reduce the noise in git blame operations and make the meaningful changes more visible.
Please let me know if any other changes are needed. For future features, we can aim to avoid adding these formatting commits entirely, which should help prevent similar issues

**Pull request merged**
